embedding_model:
  transformer: sentence-transformers/all-mpnet-base-v2
  openai_api_base: http://embedding-service:8070/v1/embeddings

dense_retriever:
  transformer: sentence-transformers/all-mpnet-base-v2

sparse_retriever:
  transformer: sentence-transformers/all-mpnet-base-v2

hybrid_retriever:
  transformer: sentence-transformers/all-mpnet-base-v2