  services:
  # FastAPI server instances
    fastapi-server:
      build:
        dockerfile: Dockerfile
      ports:
        - "8080"  # Only needed for one instance to access docs, etc.
      environment:
        - HOST=0.0.0.0
        - PORT=8090
        - REDIS_HOST=redis
      # command: uvicorn server.main:app --host 0.0.0.0 --port 8080 --workers 2
      deploy:
        replicas: 3  # Number of FastAPI instances to run
        resources:
          limits:
            cpus: '0.50'
            memory: 256M
      volumes:
        - ../src:/app
      depends_on:
        - redis

    # Nginx load balancer
    nginx:
      image: nginx:latest
      ports:
        - "80:80"  # Expose Nginx on port 80
      volumes:
        - ./nginx.conf:/src/project/docker/nginx.conf  # Map the custom Nginx config file
      depends_on:
        - fastapi-server

    # Redis for caching
    redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - app-network
      
  networks:
    app-network:
      driver: bridge
