#!/bin/bash

IP=${IP:-0.0.0.0}
PORT=${PORT:-8070}
WORKERS=${WORKERS:-1}

EMBEDDING_MODEL=${EMBEDDING_MODEL:-"sentence-transformers/all-mpnet-base-v2"}
EMBEDDING_API_KEY=${EMBEDDING_API_KEY:-"FIXME - no API key specified"}
EMBEDDING_API_URL=${EMBEDDING_API_URL:-"http://embedding-service:8070/v1/embeddings"}

cat << EOF > config/config.yaml
# Auto-generated by /entrypoint.sh:
embedding_model:
  transformer: ${EMBEDDING_MODEL}
  openai_api_key: ${EMBEDDING_API_KEY}
  openai_api_base: ${EMBEDDING_API_URL}
EOF

if [ "x$DEBUG" = "xtrue" ]; then
       cat config/config.yaml
fi

# Command to run the application
python -m uvicorn embedding_service.app.main:app --host ${IP} --port ${PORT} --workers ${WORKERS}
