networks:
  my-rag-network:
    driver: bridge # Or you can just write 'bridge' if that's the default

services:
  fastapi-rag-app: # Service A - FastAPI + RAG
    image: fastapi-rag-app # Replace with your actual FastAPI image name
    container_name: fastapi-rag-app # Optional, but helpful for clarity
    ports:
      - "8090:8090"
    networks:
      - my-rag-network # Attach to the network

  open-webui: # Service B - Open WebUI
    image: ghcr.io/open-webui/open-webui # Replace with your actual Open WebUI image name
    container_name: open-webui # Optional
    ports:
      - "3000:8080"
    networks:
      - my-rag-network # Attach to the network

  embedding-service: # Service C - Embedding Service
    image: embedding-service # Replace with your actual Embedding Service image name
    container_name: embedding-service # Optional
    ports:
      - "8070:8070"
    networks:
      - my-rag-network # Attach to the network